// <auto-generated />
using System;
using Albums.API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Albums.API.Migrations
{
    [DbContext(typeof(AlbumContext))]
    partial class AlbumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Albums.API.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a091bc10-43fd-423e-9838-3b62bd22d047"),
                            ArtistId = new Guid("6bc6a40b-6565-437f-8d08-b7985222f45d"),
                            Description = "Mind Games is the fourth studio album by English  musician John Lennon. \r\n                                    It was recorded at Record Plant Studios in New York in summer 1973. \r\n                                    The album was released in the US on 29 October 1973 and in the UK on 16 November 1973. \r\n                                    It was Lennon's first self-produced recording without help from Phil Spector.",
                            Title = "Mind Games"
                        },
                        new
                        {
                            Id = new Guid("dd331421-7d8d-493d-858b-44263ea0b7fa"),
                            ArtistId = new Guid("6bc6a40b-6565-437f-8d08-b7985222f45d"),
                            Description = "Imagine is the second studio album by English musician John Lennon, released on 9 September 1971 by Apple Records",
                            Title = "Imagine"
                        },
                        new
                        {
                            Id = new Guid("4dbc2635-ccb3-425a-9527-a4b3e7d89c17"),
                            ArtistId = new Guid("5c4bee68-77c0-4b76-9fdf-5f1750d3ab6f"),
                            Description = "Ram is a studio album by Paul McCartney and his wife Linda McCartney, released in May 1971 by Apple Records. \r\n                                    It was recorded in New York with guitarists David Spinozza and Hugh McCracken, \r\n                                    and future Wings drummer Denny Seiwell",
                            Title = "Ram"
                        },
                        new
                        {
                            Id = new Guid("9a2f2363-0f57-41f7-b397-c9c7712c4815"),
                            ArtistId = new Guid("214419f4-f64f-4af8-9de1-33a31faee1c5"),
                            Description = "All Things Must Pass is the third studio album by English rock musician George Harrison. \r\n                                Released as a triple album in November 1970, it was Harrison's first solo work after the break-up of the Beatles in April that year.",
                            Title = "All Things Must Pass"
                        },
                        new
                        {
                            Id = new Guid("d79ef7b5-ceb4-4fe8-96f5-dca2b693c356"),
                            ArtistId = new Guid("65cc0121-71e7-43c2-a934-974d2315c8f6"),
                            Description = "Sentimental Journey is the debut album by English rock musician Ringo Starr. \r\n                                    Released in 1970 as The Beatles were breaking up, Starr was the third member of the group to issue a solo recording.",
                            Title = "Sentimental Journey"
                        });
                });

            modelBuilder.Entity("Albums.API.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6bc6a40b-6565-437f-8d08-b7985222f45d"),
                            FirstName = "John",
                            LastName = "Lenon"
                        },
                        new
                        {
                            Id = new Guid("5c4bee68-77c0-4b76-9fdf-5f1750d3ab6f"),
                            FirstName = "Paul",
                            LastName = "McCartney"
                        },
                        new
                        {
                            Id = new Guid("214419f4-f64f-4af8-9de1-33a31faee1c5"),
                            FirstName = "George",
                            LastName = "Harrison"
                        },
                        new
                        {
                            Id = new Guid("65cc0121-71e7-43c2-a934-974d2315c8f6"),
                            FirstName = "Ringo",
                            LastName = "Starr"
                        });
                });

            modelBuilder.Entity("Albums.API.Entities.Album", b =>
                {
                    b.HasOne("Albums.API.Entities.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });
#pragma warning restore 612, 618
        }
    }
}
